GET http://help.nuvols.inf.br/core/api/usuario/profissional
Accept: application/json

###

PATCH http://help.nuvols.inf.br/core/api/usuario/profissional/134727b2-98d7-4d9d-98d3-c4c2b1aecfeb/
Content-Type: application/json
Accept: application/json

{
  "banco_codigo": 1,
  "banco_nome": "Banco do Brasil",
  "banco_tipo_conta": "Conta Corrente",
  "banco_numero_conta": "123456"
}

###

GET http://help.nuvols.inf.br/core/api/usuario/profissional/134727b2-98d7-4d9d-98d3-c4c2b1aecfeb

### Etapa 1 e 3 para o profissional pesquisado
GET http://help.nuvols.inf.br/core/api/atendimento/agendamento-aberto-list?fk_profissional=93e171cd-9687-4d6c-b774-1a6d9578af65&data=2021-02-01&fields=fk_profissional/id,data_solicitacao,data_agendamento,data_confirmacao,etapa

###
GET https://help.nuvols.inf.br/core/api/atendimento/agendamento-aberto-list?fk_profissional=87e64e82-81ce-4a36-b34b-a944224a2825&data=2021-02-06T12&fields=fk_profissional/id,data_solicitacao,data_agendamento,data_confirmacao,etapa

###
GET http://help.nuvols.inf.br/core/api/atendimento/agendamento-aberto-list?fk_profissional=93e171cd-9687-4d6c-b774-1a6d9578af65&data=2021-02-05&fields=fk_profissional/id,data_solicitacao,data_agendamento,data_confirmacao,etapa

###
POST https://helpto.com.br/core/api/usuario/profissional/
Content-Type: application/json
Accept: application/json

{
  "cpf":null,
  "nome":"Guilherme",
  "email":"guilherme.carvalho.carneiro@gmail.com",
  "telefone":null,
  "password":"asdf1234",
  "firebase":"QFpG67NMdEdfWSnBgUGa9agnZm12",
  "typeUser":1
}

###
GET https://helpto.com.br/core/api/usuario/profissional/49c0cd9f-8488-485f-9e6e-ba227ce7b0de/

###
PATCH https://helpto.com.br/core/api/usuario/profissional/a3f9423c-9cc5-4843-be0c-15e3e03e1d80/
Content-Type: application/json
Accept: application/json

{
  "cpf":"09809867576",
  "telefone":"(76) 54578-6889",
  "endereco":"ouiaoiudoif",
  "profissao":null,
  "categoria":"b88bede9-1a35-4137-b70b-9659c4e1f277",
  "cnpj":null
}

###
GET https://helpto.com.br/core/api/usuario/sendemail?email=guilherme.carvalho@nuvols.com.br

###
GET https://helpto.com.br/core/api/usuario/sendemail?email=desenvolvedor.net@gmail.com

###
GET https://helpto.com.br/core/api/usuario/recoverpassword/?email=aninharodrigues2@hotmail.com
Accept: application/json