# Generated by Django 2.0.6 on 2019-11-17 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=100)),
                ('token', models.TextField(editable=False, unique=True)),
                ('firebase', models.TextField(editable=False, unique=True, verbose_name='Token do usuário no Firebase')),
                ('endereco_res', models.TextField(blank=True, null=True, verbose_name='Endereço Residencial')),
                ('endereco_com', models.TextField(blank=True, null=True, verbose_name='Endereço Comercial')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=300, verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': 'Profissões',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=100)),
                ('token', models.TextField(editable=False, unique=True)),
                ('firebase', models.TextField(editable=False, unique=True, verbose_name='Token do usuário no Firebase')),
                ('foto', models.ImageField(max_length=300, upload_to='prestador/profile', verbose_name='Foto')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor da hora de trabalho')),
                ('especializacao', models.CharField(blank=True, max_length=300, null=True, verbose_name='Especialidade')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografia/Curriculo')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Profissao', verbose_name='Profissão')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
    ]
