# Generated by Django 2.1.2 on 2019-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20191117_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='firebase',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Token do usuário no Firebase'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='firebase',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Token do usuário no Firebase'),
        ),
    ]
