# Generated by Django 2.1.2 on 2019-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20191117_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='token',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='token',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
