# Generated by Django 2.1.2 on 2019-11-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20191117_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='prestador/profile', verbose_name='Foto'),
        ),
    ]
