# Generated by Django 3.0.5 on 2020-07-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200626_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Profissional aprovado?'),
        ),
    ]
