# Generated by Django 3.0.5 on 2020-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_profissional_aprovado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='firebase',
            field=models.TextField(blank=True, null=True, verbose_name='Token do usuário no Firebase'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='firebase',
            field=models.TextField(blank=True, null=True, verbose_name='Token do usuário no Firebase'),
        ),
    ]
