# Generated by Django 3.0.5 on 2020-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20200713_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
