# Generated by Django 3.1.2 on 2020-11-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_auto_20201121_1008'),
        ('usuario', '0010_auto_20200713_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='especializacao',
            new_name='especialidade',
        ),
        migrations.AddField(
            model_name='profissional',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servico.categoria', verbose_name='Categoria do serviço', null=True),
            preserve_default=False,
        ),
    ]
