# Generated by Django 3.1.2 on 2020-12-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0014_merge_20201201_1355'),
        ('usuario', '0011_auto_20201121_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='servico.categoria'),
        ),
    ]
