# Generated by Django 3.1.2 on 2020-12-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_cliente_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='categoria',
        ),
    ]
