# Generated by Django 3.1.2 on 2020-12-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_remove_cliente_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='bio',
        ),
    ]
