# Generated by Django 3.1.2 on 2020-12-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_remove_profissional_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='curtidas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profissional',
            name='favorito_clientes',
            field=models.ManyToManyField(to='usuario.Cliente'),
        ),
    ]
