# Generated by Django 3.1.2 on 2020-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_auto_20201203_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='curtidas',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
