# Generated by Django 3.1.2 on 2020-12-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_auto_20201205_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='curtidas',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='favorito_clientes',
            field=models.ManyToManyField(blank=True, to='usuario.Cliente'),
        ),
    ]
