# Generated by Django 3.1.2 on 2020-12-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_auto_20201210_2158'),
        ('usuario', '0017_auto_20201210_1323'),
    ]

    operations = [
    ]
