# Generated by Django 3.1.2 on 2020-12-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_merge_20201211_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='curtidas',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True),
        ),
    ]
