# Generated by Django 3.1.2 on 2020-12-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0015_auto_20201214_1603'),
        ('usuario', '0019_auto_20201214_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servico.categoria', verbose_name='Categoria do serviço'),
        ),
    ]
