# Generated by Django 3.1.2 on 2021-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0020_auto_20201217_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
