# Generated by Django 3.1.2 on 2021-01-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_auto_20210123_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='firebase',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Token do usuário no Firebase'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='firebase',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Token do usuário no Firebase'),
        ),
    ]
