# Generated by Django 3.1.2 on 2021-01-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0024_auto_20210123_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='profissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.profissao', verbose_name='Profissão'),
        ),
    ]
