# Generated by Django 3.1.2 on 2021-01-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0025_auto_20210125_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='valor_hora',
        ),
    ]
