# Generated by Django 3.1.2 on 2021-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0026_remove_profissional_valor_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissao',
            name='nome',
            field=models.CharField(max_length=300, unique=True, verbose_name='Profissão'),
        ),
    ]
