# Generated by Django 3.1.2 on 2021-02-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0027_auto_20210127_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cnpj',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
