# Generated by Django 3.1.2 on 2021-02-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0028_profissional_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='banco_codigo',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Código do Banco'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='banco_nome',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome do Banco'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='banco_numero_conta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Conta'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='banco_tipo_conta',
            field=models.CharField(blank=True, choices=[('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança')], max_length=50, null=True, verbose_name='Tipo da Conta'),
        ),
    ]
