# Generated by Django 3.1.2 on 2021-02-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0029_auto_20210201_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='banco_pix',
            field=models.TextField(blank=True, null=True, verbose_name='Chave do Pix'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='banco_codigo',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Número da Agência'),
        ),
    ]
