# Generated by Django 3.1.2 on 2021-02-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0030_auto_20210203_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='firebase',
            field=models.TextField(blank=True, null=True, verbose_name='Token do usuário no Firebase'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='firebase',
            field=models.TextField(blank=True, null=True, verbose_name='Token do usuário no Firebase'),
        ),
    ]
