# Generated by Django 3.1.2 on 2021-02-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0031_auto_20210212_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_token',
            field=models.TextField(blank=True, null=True, verbose_name='ID Token'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='id_token',
            field=models.TextField(blank=True, null=True, verbose_name='ID Token'),
        ),
    ]
