# Generated by Django 3.1.2 on 2021-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0033_profissional_email_cadastro_aprovado_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Longitude'),
        ),
    ]
